name: Snowflake_AutomationJobs_Project
description: test random description
version: 0.0.1
author: abhisheks+e2etests@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/Snowflake-SQLAirflow-MWAA-Automation:
    name: Snowflake-SQLAirflow-MWAA-Automation
    description: SQL Snowflake test job MWAA
    fabricUID: 20
    scheduler:
      MWAA: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 17 2 *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-10-18 06:27:11'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-18 06:22:11'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/test_Automation_Snowflake_jobs_model:
    name: test_Automation_Snowflake_jobs_model
    schema: null
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/testmodel/test_Automation_Snowflake_jobs_model.sql
    - .prophecy/ide/models/test_Automation_Snowflake_jobs_model.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-18 06:23:16'
sqlSnapshots:
  .prophecy/metadata/sqlsnapshots/test_modelanother_Automation_Snowflake_jobs_model:
    name: test_modelanother_Automation_Snowflake_jobs_model
    schema: null
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - snapshots/anothermodel/test_modelanother_Automation_Snowflake_jobs_model.sql
    - .prophecy/ide/snapshots/test_modelanother_Automation_Snowflake_jobs_model.json
    - snapshots/anothermodel/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-18 06:26:11'
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-10-18 06:22:12'
sqlSeeds:
  .prophecy/metadata/sqlseeds/qa_test_Automation_seed_job_snowflake:
    name: qa_test_Automation_seed_job_snowflake
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
      - name: name
        dataType:
          type: String
      - name: updated_at
        dataType:
          type: Date
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - seeds/qa_test_Automation_seed_job_snowflake.csv
    createdAt: '2024-10-18 06:23:28'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: abhisheks+e2etests@prophecy.io
  createdAt: '2024-10-18 06:22:11'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
